include ../Make.defines

EXERCISE = ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex14 ex15 ex16

all:$(EXERCISE)
	
ex1:ex1.o
	$(CC) $(CFLAGES) -o $@ ex1.o
ex2:ex2.o
	$(CC) $(CFLAGES) -o $@ ex2.o
ex3:ex3.o
	$(CC) $(CFLAGES) -o $@ ex3.o
ex4:ex4.o
	$(CC) $(CFLAGES) -o $@ ex4.o
ex5:ex5.o
	$(CC) $(CFLAGES) -o $@ ex5.o
ex6:ex6.o
	$(CC) $(CFLAGES) -o $@ ex6.o
ex7:ex7.o
	$(CC) $(CFLAGES) -o $@ ex7.o
ex8:ex8.o
	$(CC) $(CFLAGES) -o $@ ex8.o
ex9:ex9.o
	$(CC) $(CFLAGES) -o $@ ex9.o
ex10:ex10.o
	$(CC) $(CFLAGES) -o $@ ex10.o
ex11:ex11.o
	$(CC) $(CFLAGES) -o $@ ex11.o
ex12:ex12.o
	$(CC) $(CFLAGES) -o $@ ex12.o
ex13:ex13.o
	$(CC) $(CFLAGES) -o $@ ex13.o
ex14:ex14.o
	$(CC) $(CFLAGES) -o $@ ex14.o
ex15:ex15.o
	$(CC) $(CFLAGES) -o $@ ex15.o
ex16:ex16.o
	$(CC) $(CFLAGES) -o $@ ex16.o
clean:
	rm -f $(EXERCISE) $(CLEANFILES)